name: Main Page Deploy
on: workflow_dispatch
jobs:
  test:
    runs-on: windows-latest
    steps:
    - name: Test application
      uses: actions/checkout@v4
    - name: Install dependecies
      run: npm ci
    - name: Run Test
      run: npm run wdio ./wdio test/specs/itProger.page.js
  lint:
    runs-on: windows-latest
    steps:
    - name: Lint aplication
      uses: actions/checkout@v4
    - name: Install dependecies
      run: npm ci
    - name: Run Lint
      run: npx eslint
  buid:
    runs-on: windows-latest
    steps:
    - name: Build aplication
      uses: actions/checkout@v4
    - name: Install dependecies
      run: npm ci
    - name: Run Build
      run: npm run build .
    - name: Deploy aplication
      run: echo "Deploying..."
