name: Registration page Deploy
on: workflow_dispatch
jobs:
  test:
    runs-on: windows-latest
    steps:
      name: Test application
      uses: actions/checkout@v4
      name: Install dependecies
      run: npm ci
      name: Run Test
      run: npm run wdio ./wdio test/specs/**/*.js
  lint:
    runs-on: windows-latest
    needs: test
    steps:
      name: Lint application
      uses: actions/checkout@v4
      name: Install dependecies
      run: npm ci
      name: run Lint
      run: npm run wdio ./lint .
  build:
    runs-on: windows-latest
    needs: lint
    steps:
      name: Build application
      uses: actions/checkout@v4
      name: Install dependecies
      run: npm ci
      name: Run Build
      run: npm run wdio ./build .
      name: deploy application
      run: echo "deploying..."  